export const INSTITUTES_LIST_REQUEST = "INSTITUTES_LIST_REQUEST";
export const INSTITUTES_LIST_SUCCESS = "INSTITUTES_LIST_SUCCESS";
export const INSTITUTES_LIST_FAIL = "INSTITUTES_LIST_FAIL";

export const INSTITUTES_CREATE_REQUEST = "INSTITUTES_CREATE_REQUEST";
export const INSTITUTES_CREATE_SUCCESS = "INSTITUTES_CREATE_SUCCESS";
export const INSTITUTES_CREATE_FAIL = "INSTITUTES_CREATE_FAIL";

export const INSTITUTES_UPDATE_REQUEST = "INSTITUTES_UPDATE_REQUEST";
export const INSTITUTES_UPDATE_SUCCESS = "INSTITUTES_UPDATE_SUCCESS";
export const INSTITUTES_UPDATE_FAIL = "INSTITUTES_UPDATE_FAIL";

export const INSTITUTES_DELETE_REQUEST = "INSTITUTES_DELETE_REQUEST";
export const INSTITUTES_DELETE_SUCCESS = "INSTITUTES_DELETE_SUCCESS";
export const INSTITUTES_DELETE_FAIL = "INSTITUTES_DELETE_FAIL";
